### ISSUE TITLE
program immediately dumped stack.

### ISSUE THREAD

**Issue by richard-delorenzi** [jhh/netscape-bookmark-converter#2]
I exported bookmarks, then tried to convert them. However your program immediately dumped stack. You don't have any tests, so I can not investigate.

```
(venv) #richard@yoga:~/+Files/workshops/3rd-party/netscape-bookmark-converter$
#↳ ./convert-bookmarks.py ~/Downloads/bookmarks.html
Traceback (most recent call last):
  File "./convert-bookmarks.py", line 47, in <module>
    print(json.dumps(bookmark, sort_keys=False, indent=4))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 8, 23, 12, 25, 29, tzinfo=datetime.timezone.utc) is not JSON serializable
```

**Comment by jhh** [comment]
This was really a throw-away single use project so I will not be devoting time to working on it. I will, however, look at any pull requests.
